### ISSUE TITLE
Generator generates package.json that loads dustjs 2.7.1 despite requring < 2.7

### ISSUE THREAD

**Issue by swapnilmishra** [krakenjs/kraken-js#381]
Using kraken yoeman generator

1. generate a kraken app.
2. remove the **node_modules** folder from the generated app.
3. run **npm install**
4. run **npm start**

Gives error

```
Possibly unhandled Error: dustjs-linkedin is not a compatible version; version 2.7.0 changed the API removing dust.load. Please use dustjs-linkedin@~2.6 until new integration points are created.
    at Object.<anonymous> (/Users/swapnilmishra/Documents/node-experiment/test/node_modules/adaro/lib/patch/index.js:25:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/swapnilmishra/Documents/node-experiment/test/node_modules/adaro/lib/engine.js:23:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

```

Fixing this by changing the **dustjs-linkedin** version to  **~2.6** in package.json and then running **npm install** again gives following error.

```
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.4
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package dustjs-linkedin does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer dustjs-helpers@1.7.1 wants dustjs-linkedin@2.7 - 2.8
npm ERR! peerinvalid Peer engine-munger@0.2.6 wants dustjs-linkedin@^2.0.0
```

Really appreciate any help here. TIA.

**Comment by SimonTernoir** [comment]
You can fix this by changing both dusts-helpers and dusts-linkedin in package.json : 
```javascript
"dustjs-helpers": "~1.6.0",
"dustjs-linkedin": "~2.6",
```

**Comment by aredridel** [comment]
Indeed. It's a bug in the generator, not easy to fix because of the way npm is abstracted. @SimonTernoir has the right fix. I'm hoping to work around this with adaro 1.0 shortly.

**Comment by swapnilmishra** [comment]
@SimonTernoir @aredridel  Thanks a lot. 
The solution is working though I am wondering how it is working during the app creation with generator as npm need to resolve deps then also.

**Comment by aredridel** [comment]
The generator installs `dustjs-linkedin@^2.6`.  That resolves to 2.7, which breaks adaro. If it used ~, it'd work, but internally it's abstracted in a way that makes that difficult.

**Comment by xhe** [comment]
where can I find that package.json? I don't see the version in the root directory of installation.

**Comment by aredridel** [comment]
Of which installation?

The generator makes it in generated projects, or should.

**Comment by xhe** [comment]
where is this?
dustjs-linkedin@^2.6
I am not seeing this in package.json under project root directory, it may be inside kraken-js module or kraken-devtools? but that update will be overwriten again whenever I run npm install

**Comment by aredridel** [comment]
In the generated project, at the root, should be a `package.json` with `"dustjs-linkedin": "^2.7.1"`. Change that to `"^2.6.1"` and run `npm install`.

**Comment by xhe** [comment]
these two are manually added:
"dustjs-linkedin": "2.6.1",
"dustjs-helpers":"1.6.0",
Into package.json, there were no such module after I run yo kraken.

**Comment by aredridel** [comment]
And you did select Dust for templating?

**Comment by xhe** [comment]
Hi Aria,
I don't know if current Kraken is working fine.
1. I followed http://krakenjs.com/#documentation to get start;
2. My Node version is 0.12.4, my npm version is 2.10.1
3. I used npm install -g yo generator-kraken bower grunt-cli, then yo
kraken, Dust as template, SASS as CSS preprossor library,
4.
I saw this error:

build error

gyp ERR! stack Error: `make` failed with exit code: 2

gyp ERR! stack     at ChildProcess.onExit
(/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)

gyp ERR! stack     at ChildProcess.emit (events.js:110:17)

gyp ERR! stack     at Process.ChildProcess._handle.onexit
(child_process.js:1074:12)

gyp ERR! System Darwin 13.4.0

gyp ERR! command "node"
"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js"
"rebuild"

gyp ERR! cwd /Users/fhe/spring/kraken/MyTest/node_modules/node-sass

gyp ERR! node -v v0.12.4

gyp ERR! node-gyp -v v1.0.3

gyp ERR! not ok

Build failed

npm ERR! Darwin 13.4.0

npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
"localizr@^0.1.0" "dustjs-linkedin@~2.3.0" "dustjs-helpers@~1.2.0"
"adaro@^0.1.5"
"node-sass@^0.8.4" "requirejs@^2.1.11" "--save"

npm ERR! node v0.12.4

npm ERR! npm  v2.10.1

npm ERR! code ELIFECYCLE


npm ERR! node-sass@0.8.6 install: `node build.js`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the node-sass@0.8.6 install script 'node build.js'.

npm ERR! This is most likely a problem with the node-sass package,

npm ERR! not with npm itself.

npm ERR! Tell the author that this fails on your system:

npm ERR!     node build.js

npm ERR! You can get their info via:

npm ERR!     npm owner ls node-sass

npm ERR! There is likely additional logging output above.


npm ERR! Please include the following file with any support request:

npm ERR!     /Users/fhe/spring/kraken/MyTest/npm-debug.log

5. sudo npm install
6. npm start, go to localhost:8000, getting
The URL / had the following error Error: Cannot find module 'node-sass'.
Then npm install

7. npm start again

go to localhost:8000

page keeps loading, for a long time, never finished

I am using Mac, really don't know if kraken is a working version or not.

If current version is not working, then what version is working.

One more thing, auto generated package.json is like this:


{

    "name": "mytest",

    "version": "0.1.0",

    "description": "Test",

    "author": "FHE",

    "main": "index.js",

    "scripts": {

        "test": "grunt test"

    },

    "dependencies": {

        "kraken-js": "^1.0.1",

        "kraken-devtools": "^1.0.0",

        "engine-munger": "^0.2.0",

        "express": "^4.3.0"

    },

    "devDependencies": {

        "mocha": "^1.18.0",

        "supertest": "^0.9.0"

    },

    "generator-kraken": {

        "version": "1.1.2",

        "template": "dustjs",

        "css": "sass",

        "js": "requirejs",

        "task": "grunt"

    }

}

**Comment by xhe** [comment]
Are there way to use an older version of kraken? I just need a working
version and don't want to waste time on some not-working version

**Comment by aredridel** [comment]
Oh fun! You're running into the fact that SASS 2.x does not work with node 0.12 -- and apparently we've not tried it since 0.12 came out.

**Comment by aredridel** [comment]
Try node 0.12.4; generator-kraken 1.1.2; less, dust (manually specify 2.6 -- that bug affects all versions of the generator).

Sorry you're running into trouble!

**Comment by xhe** [comment]
how to do this: generator-kraken 1.1.2
If I use yo kraken, latest kraken is picked up.
any other command I can use to generator-kraken 1.1.2?

**Comment by aredridel** [comment]
Latest generator is 1.1.2. That will install latest kraken -- kraken itself works great in the current version. It's the configuration of the generated app that is breaking for you -- an app built from scratch without the generator would work fine.

The biggest problems you're running into are mostly around SASS -- which doesn't work with node 0.12 in version 2.x, which is what the generator configures. We don't use SASS much, so that's been neglected. Manually installing `node-sass` 3.x may work, but I haven't reviewed the API changes to see if that would work.

**Comment by xhe** [comment]
ASAP I selected LESS instead of SASS, it is fine, seemed SASS is not
supported yet

**Comment by aredridel** [comment]
https://github.com/krakenjs/kraken-devtools/pull/52 should fix the sass errors once merged.

**Comment by joeblau** [comment]
I'm running into a similar issue.  My site is in a holding pattern and I can't do any updates to the latest modules because of broken dust dependencies.

**Comment by aredridel** [comment]
Indeed. Just use the lower version -- dust 2.7 is a breaking change, and the versions that support it will be pretty different.

**Comment by aredridel** [comment]
This is fixed by https://github.com/krakenjs/generator-kraken/issues/176
